from __future__ import annotations

from pathlib import Path

import pytest

from magi_spec.core.config import MagiConfig
from magi_spec.core.errors import MagiError, MissingCredentialError
from magi_spec.engine import MagiSpecEngine
from magi_spec.providers.base import LLMProvider, ProviderFactory


class FakeOpenAIProvider(LLMProvider):
    provider_name = "openai"

    _FULL_SPEC = (
        "# Final Agent Specification\n"
        "## 1. Mission\nBuild the software.\n"
        "## 2. Background\nGenerated by MAGI.\n"
        "## 3. User Intent\nBuild package.\n"
        "## 4. Scope\n### 4.1 In Scope\n- Core.\n### 4.2 Out of Scope\n- Unrelated.\n"
        "## 5. Definitions\n- Mandatory: required.\n"
        "## 6. Evidence Summary\n- Evidence recorded.\n"
        "## 7. Mandatory Requirements\n- Implement request.\n"
        "## 8. Recommended Requirements\n- Follow conventions.\n"
        "## 9. Optional Requirements\n- Add examples if needed.\n"
        "## 10. Forbidden Behaviors\n- Do not expand scope.\n"
        "## 11. Input Contract\nAccept request inputs.\n"
        "## 12. Output Contract\nProduce documented outputs.\n"
        "## 13. Architecture\nUse existing architecture.\n"
        "## 14. Module Responsibilities\n- Keep modules focused.\n"
        "## 15. Data Flow\nInput validated, transformed, persisted.\n"
        "## 16. Error Handling Policy\nRaise actionable errors.\n"
        "## 17. Configuration Policy\nUse explicit configuration.\n"
        "## 18. Persistence / Artifact Policy\nPersist outputs as requested.\n"
        "## 19. Implementation Order\n1. Inspect. 2. Implement. 3. Test.\n"
        "## 20. Acceptance Criteria\n- Requested behavior implemented.\n"
        "## 21. Test Plan\n- Add unit tests.\n"
        "## 22. Manual Verification Checklist\n- Confirm workflow.\n"
        "## 23. Instructions for AI Coding Agent\nImplement only what is requested.\n"
    )

    def complete(
        self,
        messages: list[dict],
        *,
        model: str,
        temperature: float | None = None,
    ) -> str:
        import json as _json
        del model, temperature
        # Return appropriate response for any stage
        return _json.dumps({
            "spec_markdown": self._FULL_SPEC,
            "issues": [],
            "request_type": "feature",
            "assumptions": [],
            "blocking_questions": [],
            "pre_answers": [],
            "request_summary": "Build package.",
            "mandatory_requirements": [{"id": "REQ-001", "text": "Implement it.", "source": "user_request"}],
            "non_scope": [{"id": "NS-001", "text": "MAGI does not implement the target project directly.", "source": "system"}],
        })


def fake_openai_factory() -> ProviderFactory:
    factory = ProviderFactory()
    factory.register(FakeOpenAIProvider())
    return factory


def test_openai_default_requires_api_key(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    engine = MagiSpecEngine(config=MagiConfig.default())

    with pytest.raises(MissingCredentialError):
        engine.generate_from_text(
            text="Build package.",
            output_dir=str(tmp_path / "out"),
            web_search_mode="off",
        )


def test_openai_provider_runtime_accepts_openai_key(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    engine = MagiSpecEngine(config=MagiConfig.default(), providers=fake_openai_factory())

    result = engine.generate_from_text(
        text="Build package.",
        output_dir=str(tmp_path / "out"),
        web_search_mode="off",
    )

    assert result.status == "PASS_PENDING_USER_APPROVAL"


def test_mock_provider_does_not_require_api_key(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    engine = MagiSpecEngine(config=MagiConfig.mock())

    result = engine.generate_from_text(
        text="Build package.",
        output_dir=str(tmp_path / "out"),
        web_search_mode="off",
    )

    assert result.status == "PASS_PENDING_USER_APPROVAL"


def test_non_openai_stub_is_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    config = MagiConfig.mock()
    config.model_routing["interviewer"].provider = "anthropic"
    engine = MagiSpecEngine(config=config)

    with pytest.raises(MagiError, match="future extension stub"):
        engine.generate_from_text(
            text="Build package.",
            output_dir=str(tmp_path / "out"),
            web_search_mode="off",
        )


def test_api_rejects_invalid_web_search_mode(tmp_path: Path) -> None:
    engine = MagiSpecEngine(config=MagiConfig.mock())
    with pytest.raises(MagiError, match="Invalid web_search_mode"):
        engine.generate_from_text(
            text="Build package.",
            output_dir=str(tmp_path / "out"),
            web_search_mode="sometimes",
        )
