"""Compose the English approval candidate and final spec."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from magi_spec.core.evidence import EvidenceRegistry
from magi_spec.core.state import WorkflowState
from magi_spec.skills.registry import SkillRegistry


class SpecComposer:
    agent_id = "spec_composer"

    def __init__(self, *, skills: SkillRegistry, evidence: EvidenceRegistry) -> None:
        self.skills = skills
        self.evidence = evidence

    def compose(self, state: WorkflowState, project_manifest: dict[str, Any] | None) -> str:
        self.skills.assert_allowed(self.agent_id, "compose_final_spec")
        request = self._english_safe_user_intent(state.get("user_request", "").strip())
        project_summary = "No project folder was provided."
        if project_manifest:
            project_summary = (
                f"Project folder `{project_manifest.get('root')}` was scanned read-only. "
                f"{project_manifest.get('file_count', 0)} files were included in the manifest."
            )
        evidence_items = self.evidence.to_dict()["items"]
        evidence_lines = [self._evidence_line(item) for item in evidence_items[:12]] or [
            "- No evidence was recorded."
        ]

        return "\n".join(
            [
                "# Final Agent Specification",
                "",
                "## 1. Mission",
                "Build the software requested by the user while preserving every explicit constraint in this specification.",
                "",
                "## 2. Background",
                "This specification was generated by MAGI Spec Engine after intent analysis, evidence collection, and model-blind peer review.",
                project_summary,
                "",
                "## 3. User Intent",
                request or "The user did not provide substantive implementation details.",
                "",
                "## 4. Scope",
                "### 4.1 In Scope",
                "- Implement only the behavior explicitly requested by the user and classified as Mandatory or Recommended.",
                "- Preserve the existing project architecture unless this specification explicitly directs a change.",
                "",
                "### 4.2 Out of Scope",
                "- Do not add unrelated product features.",
                "- Do not deploy services or modify external systems unless explicitly required.",
                "",
                "## 5. Definitions",
                "- Mandatory: required for acceptance.",
                "- Recommended: valuable but not allowed to override mandatory constraints.",
                "- Optional: may be implemented only after mandatory and recommended work is complete.",
                "- Out of Scope: must not be implemented.",
                "",
                "## 6. Evidence Summary",
                *evidence_lines,
                "",
                "## 7. Mandatory Requirements",
                "- Satisfy the user's original request.",
                "- Keep changes limited to the requested implementation surface.",
                "- Preserve testability and document all assumptions that affect behavior.",
                "",
                "## 8. Recommended Requirements",
                "- Follow existing repository conventions, naming, and dependency patterns.",
                "- Prefer small, focused modules over broad mixed-responsibility code.",
                "",
                "## 9. Optional Requirements",
                "- Add extra examples only when they clarify the requested behavior without expanding scope.",
                "",
                "## 10. Forbidden Behaviors",
                "- Do not implement unrelated features.",
                "- Do not ignore user constraints.",
                "- Do not hide unresolved blockers.",
                "- Do not rely on model identity or routing authority as a reason for implementation decisions.",
                "",
                "## 11. Input Contract",
                "Accept the inputs described by the user's request. Validate unsupported inputs with clear errors.",
                "",
                "## 12. Output Contract",
                "Produce the outputs described by the user's request. Avoid undocumented side effects.",
                "",
                "## 13. Architecture",
                "Use the repository's existing architecture as the default. Add new boundaries only when they reduce complexity or enforce a required contract.",
                "",
                "## 14. Module Responsibilities",
                "- Keep CLI or UI code thin.",
                "- Put reusable business logic in package modules.",
                "- Keep persistence, configuration, and external integrations behind explicit interfaces.",
                "",
                "## 15. Data Flow",
                "Input should be validated, transformed through explicit domain logic, persisted or emitted through documented outputs, and verified by tests.",
                "",
                "## 16. Error Handling Policy",
                "Raise actionable errors for missing inputs, invalid configuration, unsupported files, failed writes, and unsafe operations.",
                "",
                "## 17. Configuration Policy",
                "Use explicit configuration for behavior that differs by environment. Do not hard-code credentials.",
                "",
                "## 18. Persistence / Artifact Policy",
                "Persist user-facing outputs only where requested. Do not mutate unrelated project files.",
                "",
                "## 19. Implementation Order",
                "1. Inspect the existing project structure.",
                "2. Implement the narrowest complete change.",
                "3. Add or update focused tests.",
                "4. Run verification commands and report any commands that could not be run.",
                "",
                "## 20. Acceptance Criteria",
                "- The requested behavior is implemented.",
                "- Existing behavior outside the request remains intact.",
                "- Tests cover the changed behavior.",
                "- Any assumptions or skipped verification steps are reported.",
                "",
                "## 21. Test Plan",
                "- Add unit tests for new domain behavior.",
                "- Add CLI or integration tests when user-visible workflows change.",
                "- Run the relevant existing test suite.",
                "",
                "## 22. Manual Verification Checklist",
                "- Confirm the main user workflow works end to end.",
                "- Confirm errors are readable and actionable.",
                "- Confirm generated or modified files are in the expected locations.",
                "",
                "## 23. Instructions for AI Coding Agent",
                "Implement the requested project changes only. Do not broaden scope, do not skip tests, and do not treat this instruction document as permission to modify unrelated systems.",
                "",
            ]
        )

    @staticmethod
    def english_only(text: str) -> bool:
        return not any("\uac00" <= char <= "\ud7a3" for char in text)

    @classmethod
    def _english_safe_user_intent(cls, text: str) -> str:
        if not text:
            return "The user did not provide substantive implementation details."
        if cls.english_only(text):
            return text
        return (
            "The original request contains non-English text and is preserved in "
            "`raw/user_request.md`. Follow the English requirements in this "
            "document and consult the preserved raw request only as source evidence."
        )

    @classmethod
    def _evidence_line(cls, item: dict[str, Any]) -> str:
        summary = str(item.get("summary", ""))
        if not cls.english_only(summary):
            summary = "Non-English evidence summary is preserved in the evidence registry."
        return f"- {item.get('evidence_id')}: {item.get('evidence_type')} - {summary}"

    @staticmethod
    def final_path(output_dir: str) -> Path:
        return Path(output_dir) / "final" / "FINAL_AGENT_SPEC.md"
